name: push
on:
  push:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  push:
    uses: pilotgab/actions-templates/.github/workflows/publish.yaml@main

  staging-deploy:
    needs: push
    if: contains('refs/heads/dev', github.ref)
    uses: pilotgab/actions-templates/.github/workflows/trigger-gitops.yaml@main
    with:
      environment: staging
    secrets: inherit

    
  testing-QA-deploy:
    needs: push
    if: contains('refs/heads/feature', github.ref)
    uses: pilotgab/actions-templates/.github/workflows/trigger-gitops.yaml@main
    with:
      environment: testing/QA
    secrets: inherit
    
  prod-deploy:
    needs: push
    if: contains('refs/heads/master', github.ref)
    uses: pilotgab/actions-templates/.github/workflows/trigger-gitops.yaml@main
    with:
      environment: prod
    secrets: inherit

